### ISSUE TITLE
Модель не должна знать о DOM

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/slider#12]
```
    this.data = {
      $slider: options.slider,
```
это что, jQuery object передается?
не вижу кстати, чтобы он моделью вообще использовался

**Comment by chmnkh** [comment]
```
showConfigPanel: options.showConfigPanel,
handleValueHide: options.handleValueHide,
verticalOrientation: options.verticalOrientation,
```
насчет этого флага тоже сомнения большие
почему модель знает об отображении какой-то там панели, о каком-то хэндлере, об ориентации?

**Comment by chmnkh** [comment]
```
searchPositionWhenMoving({ coordinatesInsideTheSlider, sliderWidth, elementName, data })
```
это модель знает что кто-то двигает слайдер? его ширину и имя элемента?

Модель не должна ничего знать о том, что с связано с каким-то гуем, вьюхой, тем что юзер сейчас двигае слайдер, и так далее. Все что делает модель - это что-то считает, и все. Она не должна думать, кто там что двигает и так далее. Она тупо считает что-то.

**Comment by ValentinAlexandrovich** [comment]
Тут скорее проблема с именованием. Передача параметров в модель в частности и слайдера, происходит при инициализации слайдера, модель является хранилищем параметров которые используются для расчетов и отображении во вьюхах. К $slider модель относит не более чем как полю с объектом.

**Comment by chmnkh** [comment]
Короче, на первый взгляд ничего особо не поменялось, и все так же есть какие-то намеки на то, что модель каким-то образом знает про какие-то рендеры, клики и т.д.
Кстати, обрати внимание на ишью #14, потому что сейчас очень сложно смотреть твой код.

**Comment by ValentinAlexandrovich** [comment]
При создании архитектуры следует учесть, что проверку для наблюдателя лучше реализовать в отдельном классе, от которого будет наследоваться класс EventObserver и вызывать метод проверки на допустимость вызова метода обсервера в notify. Также предусмотреть автоматическое определение отправителя в EventObserver, как вариант можно воспользоваться таким примером архитектуры.
![xasx](https://user-images.githubusercontent.com/31854808/47277538-78789780-d5eb-11e8-995b-80e7b30de8b2.jpg)

**Comment by Frolikow** [comment]
test

**Comment by chmnkh** [comment]
1) ```updateViews```
2) ```updateValuesWhenClick```
я уже вижу какую-то вьюху, хотя еще даже не особо начал читать)
