### ISSUE TITLE
Обработчики событий вынести в отдельные методы

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/slider#13]

**Comment by Frolikow** [comment]
Как сейчас сделано - правильно? Или, если не правильно, подскажи пожалуйста как должно быть)

**Comment by chmnkh** [comment]
нет, неправильно
пример:
```
    this.$firstHandle.mousedown((event) => {
      this._moveHandleWhenDragging({ event, $currentItem: this.$firstHandle });
    });
```
должно быть:
```
    this.$firstHandle.mousedown(this.handleFirstHandleMousedown);
```

**Comment by chmnkh** [comment]
С биндами хэндлеров можно сделать несколько вещей:
1) в каком-то методе их забиндить, и при инициализации его вызвать, чтобы потом при навешивании обработчиков бинды в глаза не лезли
2) можешь поискать декораторы для бинда, чтобы просто рядом с методом написать что-то типа @bind, и все
3) можешь заюзать вот это вот, например: https://babeljs.io/docs/en/babel-plugin-proposal-class-properties (см. boundFunction и консоль логи)

**Comment by chmnkh** [comment]
```
  $switchVisibilityTooltips.change(this._handleSwitchVisibilityTooltipsOnChange.bind(this, $switchVisibilityTooltips));
 _handleSwitchVisibilityTooltipsOnChange($switchVisibilityTooltips)
```

в обработчики события же можно получить элемент, на котором событие вызвано, почему ты через бинд его туда прокидываешь?
