### ISSUE TITLE
eventEmiter

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/slider#16]
![image](https://user-images.githubusercontent.com/31949379/46902729-40d76480-cef4-11e8-937c-fb7fa2ace981.png)
Если у инстанса есть метод = name, но при этом не предназначенный для прослушки этого событитя, то возникнет ошибка. Проблема класса EventEmitter
 в том, что наблюдателем является инстанс. Будет лучше если наблюдателем сможет стать любая функция, любой метод.

**Comment by ValentinAlexandrovich** [comment]
Спорно, это легче пофиксить и в имеющейся архитектуре, чем следить за именованием евентов, чтобы они не совпали где это не предусмотрено логикой.

**Comment by Geksanit** [comment]
![image](https://user-images.githubusercontent.com/31949379/47949058-3cd8b880-df6f-11e8-94e8-a839fb822cd2.png)
это что за безобразие?

**Comment by Frolikow** [comment]
> unSubscribe - это одно слово 'unsubscribe'

исправил.

![](https://user-images.githubusercontent.com/31949379/47949058-3cd8b880-df6f-11e8-94e8-a839fb822cd2.png)
этого кода в процессе рефакторинга не осталось)

> `notify(methodName, data) {` EventEmitter ничего не знает о методах

Это вопрос? Поясни пожалуйста, не совсем понятно, что ты хотел сказать
