### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/slider#18]
Нужно упростить код

**Comment by Geksanit** [comment]
`const { minimum, maximum, value, valueRange, step } = options;
    this.pluginOptions = { minimum, maximum, value, valueRange, step };`
сможешь сделать тоже самое в одну строку? )))

**Comment by Frolikow** [comment]
> ![image](https://user-images.githubusercontent.com/31949379/47949007-457cbf00-df6e-11e8-8322-9ce061a63006.png)
> сможешь сделать тоже самое в одну строку? )))
> это действительно pluginOptions ?

Это в процессе рефакторинга было исправлено)
