### ISSUE TITLE
рефакторинг метода модели

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/slider#19]
![image](https://user-images.githubusercontent.com/31949379/49066953-3af3d380-f255-11e8-975b-4380f9b17ae4.png)
1. Комментарии не должны дублировать код. Это будет ещё больше заметно, если переменную `relativeCoordinates` - назвать так, как ты её называешь в комментариях.
2. Излишне сложное условие. Зачем проверять клик справа или слева ? Достаточно проверки близости.

**Comment by Geksanit** [comment]
3. тут встречается  слово клик, но модель не должна знать что происходят именно клики.

**Comment by Geksanit** [comment]
В именах методов не нужно The `_calculateTheValueForTheHandle`
Остальное в модели вроде норм.

**Comment by chmnkh** [comment]
вот это вот:
```
    this.modelData.minimum = (newDataToUpdateTheState.minimum === undefined) ? this.modelData.minimum : newDataToUpdateTheState.minimum;
    this.modelData.maximum = (newDataToUpdateTheState.maximum === undefined) ? this.modelData.maximum : newDataToUpdateTheState.maximum;
    this.modelData.value = (newDataToUpdateTheState.value === undefined) ? this.modelData.value : newDataToUpdateTheState.value;
_бла бла бла_
```
можно переписть на 
```
this.modelData = { ...this.modelData, ...newDataToUpdateState };
```
в целом такой код, как в самом верхнем примере, где куча одинаковых операций подряд идут, должен у тебя как минимум сомнения вызывать)

п.с.: заметь, что я The убрал из названия: писать во всяких именах артикли - это черезчур)

**Comment by chmnkh** [comment]
```
this.modelData = {
      minimum: options.minimum,
      maximum: options.maximum,
      value: options.value,
      valueRange: options.valueRange,
      step: options.step,
      rangeStatus: options.rangeStatus,
      visibilityTooltips: options.visibilityTooltips,
      verticalOrientation: options.verticalOrientation,
    };
```
то же самое, что и в комменте выше
