### ISSUE TITLE
Разобраться с _checkIncomingData

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/slider#21]
Сейчас этот метод у тебя как работает:
1) пишутся значения в this.modelData, которые пришли откуда-то там
2) вызывается checkIncomingData, который проверяет то, что написано сейчас в this.modelData, и, если что-то не так, переписывает его

Не очень хорошо получается, что ты в систему вообще какие-то инвалидные данные можешь пустить.

Более логичным на мой взгляд был бы подход, при котором у тебя перед записью данных в modelData отрабатывал бы какой-то фильтр, который бы как раз смотрел, какие данные пропустить в modelData. Таким образом, у тебя в modelData находились бы всегда валидные данные, а не так, что ты туда записал что-то, а потом их провалидировал, и оказалось, что туда записалась какая-то фигня, и надо их переписать. 

Далее, у тебя вообще говоря этот метод несколько вещей сразу делает: во-первых, проверяет то, что у тебя все нужные поля проинициализированы (`this.modelData.minimum = (this.modelData.minimum === undefined) ? 1 : this.modelData.minimum;` - подобные строки), а во-вторых, проверяет, что у тебя все поля - валидные (всякие там проверки максимумов и минимумов и т.п.). По сути то, первое тебе нужно только при инициализации modelData какими-то опциями, передаваемыми в конструктор, чтобы проверить, что все опции пришли, а второе - как при инициализации так и при апдейте. Хотя вызывается метод и при инициализации и при апдейте. Получается при апдейте какая-то ненужная работа еще происходит в виде проверки на все эти андефайнды.

Итого я тебе предлагаю сделать так: разбить этот метод на две функции:
Функция 1: берет объект типа newModelData (имеется в виду объект, содержимое которого должно потом в this.modelData попасть при апдейте или при инициализации), валидирует поля этого объекта (а точнее его созданной копии, чтобы функция не меняла по ссылке переданный ей объект), и возвращает новый объект со всеми валидными полями.
Функция 2: берет опции при инициализации, чекает, передали ли все что надо (опять же работает с копией), а дальше валидирует объект с помощью функции 1. Потом этот объект итоговый возвращает.

Причем я бы вынес эти функции вообще из класса модели, чтобы ее разгрузить, и положил бы рядом с Model.js в какой-нибудь modelDataValidators.js файл.

Т.е. при инициализации ты будешь использовать фунцию 2 (все имена примерные, может быть ты лучше придумаешь):
```
this.modelData = validateOptions(options);
```
а при апдейте функцию 1:
```
this.modelData = validateUpdateData(updateData);
```

По итогу ты модель разгрузишь, ибо все это отдельно вынесешь, + у тебя не будут в систему инвалидные данные вообще попадать, не будет этой странной последовательности: "записать в modelData все подряд данные, потом проверить, записали ли то что надо или нет, и если что переписать"

**Comment by Frolikow** [comment]
Написал твой вариант: первая функция проверяет наличие всех значений для инициализации. и запускает вторую функцию, которая уже проверяет корректность всех значений.

**Comment by chmnkh** [comment]
1) function checkDataForInitialization(incomingData) 
1.1) лучше назвать проще: validateInitialData
1.2) 
```
  checkDataForUpdate(dataForInitialization);
  return dataForInitialization;
```
У тебя checkDataForUpdate объект dataForInitialization не поменяет (причем я тебя специально попросил так написать, потому что мутировать входные параметры - это жуть как плохо), так что то, что ты его здесь вызываешь и никуда не кладешь результат - это крик в пустоту. 
1.3) 
```
  dataForInitialization.minimum = (dataForInitialization.minimum === undefined) ? 1 : dataForInitialization.minimum;
  dataForInitialization.maximum = (dataForInitialization.maximum === undefined) ? 10 : dataForInitialization.maximum;
```
про это: не знаю почему я сразу не написал (вроде бы хотел, уже не помню), но все эти проверки можно намного проще написать:
```
const initialData = { ...defaultInitialData, ...incomingData };
```
где defaultInitialData - константа с initial датой по умолчанию (как раз где minimum: 1, maximum: 10 и так далее), ее можешь хоть рядом с этим валидатором положить
вот эта одна строчка заменит всю эту портянку с проверками на undefined.
Тогда кстати тебе в этой функции и не придется создавать копию никакую, и вообще функция в пару строчек будет.

**Comment by chmnkh** [comment]
2) function checkDataForUpdate(incomingData)
2.1) не совсем корректное название, у тебя же при инициализации тоже эта проверка есть, а не только при апдейте. Если дать общее название типа validateIncomingData - будет лучше.
2.2) у тебя адски много раз повторяется dataForUpdate.*, если ты деструктурируешь:
```
const { minimum, maximum, etc... } = dataForUpdate;
```
то уже сильно легче станет читаться
2.3) ```dataForUpdate.minimum = isNumeric(dataForUpdate.minimum) ? dataForUpdate.minimum : 1;```
опять, же, такой тернарник сильно хуже читался, чем читалась бы такая строчка:
```
if (!isNumeric(minumum)) {
   dataForUpdate.minimum = 1; 
}
```
вместо единички, кстати, было бы значение константы, про которую я писал в комменте выше.

**Comment by chmnkh** [comment]
3) Другое
3.1) isValueOfStepWithinAllowedInterval - в инглише можно вместо ValueOfStep сказать StepValue - смысл будет ровно один и тот же, "значение шага" (перевод как бы справа налево). Лучше стараться придерживаться второго варианта именования, потому что он тупо более легковесный.
3.2) isValuesWithinAllowedInterval - values - множественное число, а значит вспомогательный глагол не is, а are (а вообще там по смыслу видимо опечатка, потому что значение одно).
3.3) 
```
    const verifiedData = checkDataForUpdate(newDataToUpdateState);
    this.modelData = { ...verifiedData };
```

а зачем ты тут вообще копию создаешь?) да и вообще в общем-то было не обязательно переменную эту создавать, можно было сразу выхлоп функции пустить в modelData.

**Comment by chmnkh** [comment]
```
const defaultInitialData = {
  minimum: 1,
  maximum: 10,
  step: 1,
};
defaultInitialData.value = defaultInitialData.minimum;
defaultInitialData.valueRange = defaultInitialData.maximum;
```

а почему ты сразу не написал?
```
const defaultInitialData = {
  minimum: 1,
  maximum: 10,
  step: 1,
  value: 1,
  valueRange: 10,
};
```
