### ISSUE TITLE
вместо delete лучше использовать деструктуризацию.

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/slider#23]
![image](https://user-images.githubusercontent.com/31949379/49374987-95999d80-f735-11e8-8fb6-8e78a843229b.png)
Тут хорошо видно что не отправляется, а что же всё-таки отправляется не видно))

**Comment by Geksanit** [comment]
Похоже что ты не знаешь что такое деструктуризация объектов.
лучше деструктуризировать так:
`
const { secondRelativePosition, value, valueRange} = newData;
`
а потом делать так:
`
const dataForSlider = {
  coordinatesSecondHandle: secondRelativePosition,
  value,
  valueRange,
}
`

**Comment by Frolikow** [comment]
Я знаю, что такое деструктуризация объектов) У меня она встречается в проекте, просто в этом месте не сообразил с помощью деструктуризации сделать)
