### ISSUE TITLE
Слайдер ломается

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/slider#25]
1. Ставишь минимальное значение 4
2. Ставишь максимальное значение 7
3. Ставишь шаг 3
4. Пытаешься двигать хэндлами, они не двигаются

**Comment by Frolikow** [comment]
Ну это ведь логично, от 4 до 7 ровно один шаг и получается( если шаг = 3)

**Comment by chmnkh** [comment]
да, я упоролся, сорян
