### ISSUE TITLE
Codestyle

### ISSUE THREAD

**Issue by alextsk** [Frolikow/slider#33]
https://github.com/Frolikow/slider/blob/90ab676ec87a3d8561c8ec50a276d3488b1dd79d/src/plugins/slider-plugin/ViewSlider/ViewSlider.js#L28

такие длинные импорты нужно разбивать по одному на строку. а в данном примере еще можно их деструктурировать прямо в аргументах функции

https://github.com/Frolikow/slider/blob/90ab676ec87a3d8561c8ec50a276d3488b1dd79d/src/plugins/slider-plugin/ViewSlider/ViewSlider.js#L95

при чтении в гитхабе * this.stepWidth - не влезло на экран, выглядело странно. такие тоже бы желательно переносить

хорошо когда имена документируют код, но я считаю иногда и с этим можно перестараться и ухудшить читабельность:

isPositionIsGreaterLastValue , isValueIsGreaterLastValue - грамматически не очень(2 is) и пересказывает код, offLimits или outOfBounds рассказало бы о намерении 

arrayOfPossibleHandleValues - нужно ли нам знать что это array? может это Set. почему только handle, для инпутов уже не подходит?  possibleSliderValues мне кажется достаточно 

_handleHandleMousedown - хендл хендла? -я понимаю о чем тут, но выглядит как опечатка, может надо было либо ручки по другому назвать либо события через on? это просто к размышлению

_getCoordinatesOfElementInsideWindow огромное название для такой простой функции

_createSliderElement - что кроме element мы можем create?

**Comment by Frolikow** [comment]
Не совсем понял вопроса

> _createSliderElement - что кроме element мы можем create?

**Comment by alextsk** [comment]
в смысле Element здесь обязательно? что то еще создается?

**Comment by Frolikow** [comment]
создается именно элемент слайдера

**Comment by alextsk** [comment]
те createSlider считаешь тут не подойдет?

**Comment by Frolikow** [comment]
у меня на выходе ведь sliderElement. кажется логичным точное название

**Comment by Znack** [comment]
`_createSliderElement` — ну тут можно и с `element`, так как потенциально у тебя действительно слайдер можно как просто экземпляр класса создавать (у которого будет свойство `element`, например) и тд, я бы конкретно тут не обязывал убирать слово `element` :)

**Comment by Znack** [comment]
А остальные комментарии прямо не просто грамотные, но ещё и хорошо описаны, респект :)
