### ISSUE TITLE
Тесты не сработали

### ISSUE THREAD

**Issue by alextsk** [Frolikow/slider#34]
![image](https://user-images.githubusercontent.com/16453186/52217410-f4f96280-28ca-11e9-9f05-a08bdb93db96.png)

**Comment by Frolikow** [comment]
Странно..
![image](https://user-images.githubusercontent.com/25764783/52287510-df546d80-299c-11e9-98bf-b96adbd92c74.png)

**Comment by alextsk** [comment]
возможно win не так читает пути. ок, кросспатформенности не было в условиях)
