### ISSUE TITLE
сложные логические условия нужно вычислять отдельно

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/slider#5]
![image](https://user-images.githubusercontent.com/31949379/45548175-906f3580-b84d-11e8-8338-7ef640bbc883.png)
Такие условия лучше вычислять в отдельную переменную, это есть в стандартах.

**Comment by Frolikow** [comment]
исправил. Но закомитил вместе с другой проблемой ( [комит](https://github.com/Frolikow/slider/commit/a48c13c62512c17440bad8ce6c15b3f9f0cd8227) )
