### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/slider#6]
![image](https://user-images.githubusercontent.com/31949379/45548554-de386d80-b84e-11e8-8dcf-3f72cca9d036.png)
Вот этот код в модели говорит о том, что ты не знаешь зачем нужна модель. И вообще что такое mvc. Расскажи в кратце как ты понял mvc. Какую роль играет model, controller, view?

**Comment by Geksanit** [comment]
Другие классы тоже не соответствую mvc.

**Comment by Frolikow** [comment]
Вкратце, model для хранения всех данных и функций в ней, view для создания html, а controller для слежки за событиями на DOM-элементах и вызова функций из модели.

Model знает только о своем существовании, как и view, а controller знает о model и view, и работает с ними.

**Comment by Geksanit** [comment]
Тогда зачем модели знать о DOM элементах, атрибутах? Почему модель сама добывает себе инфу? В модели вообще не должен использоваться jQuery.
Контроллер тоже ничего не должен знать о DOM. Работать с DOM должна вью, т.е. не только рендерить пару элементов. Изучи MVC по лучше, это сложная тема.

**Comment by Frolikow** [comment]
спасибо.

**Comment by ValentinAlexandrovich** [comment]
Вот еще две хорошие статьи 
https://habrahabr.ru/post/321050/
https://habrahabr.ru/post/276593/

**Comment by Frolikow** [comment]
Спасибо

**Comment by Frolikow** [comment]
Ишью еще актуально?
